package failchat.chat

import failchat.Origin
import failchat.chat.badge.Badge
import failchat.emoticon.Emoticon
import java.time.Instant

/**
 * A message from a chat of some origin.
 * */
open class ChatMessage(
        /** An internal id generated by the application. */
        val id: Long,

        /** The origin of the message. */
        val origin: Origin,

        /** The author of the message. */
        val author: Author,

        /** The text of the message. */
        var text: String,

        /** The time when the message was received. */
        val timestamp: Instant = Instant.now()
) {

    /**
     * Could contains next elements:
     * - [Emoticon]
     * - [Link]
     * - [Image]
     * */
    val elements: List<MessageElement>
        get() = mutableElements
    private val mutableElements: MutableList<MessageElement> = ArrayList(5)

    /** Badges of the message. */
    val badges: List<Badge>
        get() = mutableBadges
    private val mutableBadges: MutableList<Badge> = ArrayList(3)

    var highlighted: Boolean = false
    var highlightedBackground: Boolean = false

    /**
     * @return formatted string for added element.
     * */
    fun addElement(element: MessageElement): String {
        mutableElements.add(element)
        return Elements.label(mutableElements.size - 1)
    }

    fun replaceElement(index: Int, replacement: MessageElement): Any? {
        return mutableElements.set(index, replacement)
    }

    fun addBadge(badge: Badge) {
        mutableBadges.add(badge)
    }

    override fun toString(): String {
        return "ChatMessage(id=$id, origin=$origin, author=$author, text='$text', timestamp=$timestamp, " +
                "badges=$badges, mutableElements=$mutableElements, highlighted=$highlighted, " +
                "highlightedBackground=$highlightedBackground)"
    }

}
